services:
  postgres:
    image: postgres:17.5
    restart: always
    networks:
      - tripg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - /home/tripg/workspace/docker-data/postgresql:/var/lib/postgresql/data

networks:
  tripg:
    external: true
