version: '3'

volumes:
  mysql_data:
    driver: local

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    restart: always
    networks:
      - keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: 127.0.0.1
      KC_DB_URL_PORT: 3306
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: 'true'
    ports:
      - 8080:8080

networks:
  keycloak:
    external: true