services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    restart: always
    networks:
      - tripg
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://192.168.1.7:5432/keycloak
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_PORT: 8080
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: 'true'
    ports:
      - 8080:8080

networks:
  tripg:
    external: true