version: '3.7'
services:
  jaeger:
    restart: always
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831"
      - "6832:6832/udp"
      - "16686:16686"
      - "5778:5778"
      - "4317:4317"
      - "14250:14250"
    networks:
      - jaeger

networks:
  jaeger:
    external: true