services:
  dragonfly:
    container_name: dragonflydb
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    restart: always
    network_mode: "host"
    volumes:
      - dragonflydata:/data


volumes:
  dragonflydata: