services:
  minio:
    image: minio/minio:latest
    restart: always
    networks:
      - tripg
    ports:
      - "9000:9000"
      - "9001:9001"
    container_name: minio
    volumes:
      - /home/tripg/workspace/docker-data/minio-data:/data
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: server --console-address ":9001" /data

networks:
  tripg:
    external: true