version: "3"
services:
  meilisearch:
    container_name: meili
    stdin_open: true
    tty: true
    ports:
      - 7700:7700
    environment:
      - MEILI_ENV=development
    volumes:
      - ./meili_data:/meili_data
    image: getmeili/meilisearch:v1.12
    restart: always